version: "2.1"

networks:
  marketfish:

services:
  marketfish:
    build: .
    container_name: "marketfish"
    restart: always
    networks:
      - marketfish

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
    networks:
      - marketfish


